import Foundation

enum PrivacyRejectionReason: Equatable, Sendable {
    case recordingPaused
    case ignoredApplication
    case passwordManager
    case sensitiveContent
    case transientContent
}

enum PrivacyDecision: Equatable, Sendable {
    case allow
    case reject(PrivacyRejectionReason)
}

struct PrivacyFilter: Sendable {
    private let passwordManagerBundlePrefixes = [
        "com.1password.",
        "com.agilebits.onepassword",
        "com.bitwarden.",
        "com.dashlane.",
        "com.lastpass."
    ]

    private let concealedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType"
    ]

    private let transientTypes: Set<String> = [
        "org.nspasteboard.TransientType",
        "com.apple.is-remote-clipboard"
    ]

    func decision(for candidate: ParsedClipboard, settings: AppSettings) -> PrivacyDecision {
        if settings.recordingPaused { return .reject(.recordingPaused) }

        if let bundleIdentifier = candidate.source.bundleIdentifier {
            let normalized = bundleIdentifier.lowercased()
            if settings.ignoredBundleIdentifiers.map({ $0.lowercased() }).contains(normalized) {
                return .reject(.ignoredApplication)
            }
            if passwordManagerBundlePrefixes.contains(where: { normalized.hasPrefix($0) }) {
                return .reject(.passwordManager)
            }
        }

        if settings.ignoreSensitiveContent && !candidate.declaredTypes.isDisjoint(with: concealedTypes) {
            return .reject(.sensitiveContent)
        }
        if settings.ignoreTransientContent && !candidate.declaredTypes.isDisjoint(with: transientTypes) {
            return .reject(.transientContent)
        }
        return .allow
    }
}

