name: WPaste
options:
  bundleIdPrefix: com.chujianyun
  deploymentTarget:
    macOS: "15.0"
settings:
  base:
    SWIFT_VERSION: "6.0"
    DEVELOPMENT_TEAM: 7PXD675DGC
    CODE_SIGN_STYLE: Manual
    CODE_SIGN_IDENTITY: DC86852A3142B093C0D6EF89F9978BC63349E0AF
    CODE_SIGNING_ALLOWED: YES
    MARKETING_VERSION: "0.1.1"
    CURRENT_PROJECT_VERSION: "2"
configFiles:
  Debug: Config/Debug.xcconfig
  Release: Config/Release.xcconfig
targets:
  WPaste:
    type: application
    platform: macOS
    sources:
      - path: WPaste
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.chujianyun.wpaste
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_LSUIElement: YES
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.utilities
  WPasteTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: WPasteTests
    dependencies:
      - target: WPaste
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
schemes:
  WPaste:
    build:
      targets:
        WPaste: all
        WPasteTests: [test]
    test:
      targets:
        - WPasteTests
